services:
  db:
    image: postgres:17-alpine
    container_name: zharinoff_bot_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - zharinoff_bot_data:/var/lib/postgresql/data
    networks:
      - zharinoff_bot_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  zharinoff_bot_data:
    name: zharinoff_bot_data

networks:
  zharinoff_bot_backend:
    driver: bridge
    name: zharinoff_bot_backend