"""init revision

Revision ID: 4a07768363b4
Revises: 
Create Date: 2026-09-08 09:15:26.131413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a07768363b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vk_group_id', sa.Integer(), nullable=True),
    sa.Column('vk_api_token', sa.String(), nullable=True),
    sa.Column('is_bot_active', sa.Boolean(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_vk_group_id'), 'tenants', ['vk_group_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_vk_user_id'), 'users', ['vk_user_id'], unique=True)
    op.create_table('tenants_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'game_id', name='uq_tenants_games_group_game')
    )
    op.create_index(op.f('ix_tenants_games_game_id'), 'tenants_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_tenants_games_group_id'), 'tenants_games', ['group_id'], unique=False)
    op.create_index('ix_tenants_games_group_id_game_id', 'tenants_games', ['group_id', 'game_id'], unique=False)
    op.create_index(op.f('ix_tenants_games_id'), 'tenants_games', ['id'], unique=False)
    op.create_table('tenants_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_tenants_users_group_user')
    )
    op.create_index(op.f('ix_tenants_users_group_id'), 'tenants_users', ['group_id'], unique=False)
    op.create_index('ix_tenants_users_group_id_user_id', 'tenants_users', ['group_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_tenants_users_id'), 'tenants_users', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_users_user_id'), 'tenants_users', ['user_id'], unique=False)
    op.create_table('users_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('statistic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_users_games_user_game')
    )
    op.create_index(op.f('ix_users_games_game_id'), 'users_games', ['game_id'], unique=False)
    op.create_index(op.f('ix_users_games_id'), 'users_games', ['id'], unique=False)
    op.create_index(op.f('ix_users_games_user_id'), 'users_games', ['user_id'], unique=False)
    op.create_index('ix_users_games_user_id_game_id', 'users_games', ['user_id', 'game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_games_user_id_game_id', table_name='users_games')
    op.drop_index(op.f('ix_users_games_user_id'), table_name='users_games')
    op.drop_index(op.f('ix_users_games_id'), table_name='users_games')
    op.drop_index(op.f('ix_users_games_game_id'), table_name='users_games')
    op.drop_table('users_games')
    op.drop_index(op.f('ix_tenants_users_user_id'), table_name='tenants_users')
    op.drop_index(op.f('ix_tenants_users_id'), table_name='tenants_users')
    op.drop_index('ix_tenants_users_group_id_user_id', table_name='tenants_users')
    op.drop_index(op.f('ix_tenants_users_group_id'), table_name='tenants_users')
    op.drop_table('tenants_users')
    op.drop_index(op.f('ix_tenants_games_id'), table_name='tenants_games')
    op.drop_index('ix_tenants_games_group_id_game_id', table_name='tenants_games')
    op.drop_index(op.f('ix_tenants_games_group_id'), table_name='tenants_games')
    op.drop_index(op.f('ix_tenants_games_game_id'), table_name='tenants_games')
    op.drop_table('tenants_games')
    op.drop_index(op.f('ix_users_vk_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_vk_group_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
